version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    command: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_USER: otus_user
      POSTGRES_PASSWORD: otus_password
      POSTGRES_DB: calendar_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U otus_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
  calendar:
    build:
      context: ..
      dockerfile: build/Dockerfile
    restart: always
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - migrate
  scheduler:
    build:
      context: ..
      dockerfile: build/scheduler/Dockerfile
    restart: always
    depends_on:
      - migrate
      - rabbitmq

  migrate:
    image: migrate/migrate
    volumes:
      - ../migrations:/migrations
    entrypoint:
      - "migrate"
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://otus_user:otus_password@db:5432/calendar_test?sslmode=disable"
      - "up"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  sender:
    build:
      context: ..
      dockerfile: build/sender/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - migrate
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  test_itgr:
    container_name: test_itgr
    build:
      context: ..
      dockerfile: build/test/Dockerfile
    depends_on:
      - calendar

volumes:
  postgres-data:
  migrations: