version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  calendar:
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: